// VueStudent/src/components/SimpleHelloWorld.vue
<template>
  <hr/>
  <h3>SimpleHelloWorld Component</h3>
  <p>Hello, World!</p>
  <p>{{new Date().toString()}}</p>
  <hr/>
</template>

<script>
  const SimpleHelloWorld = {
    data() {
      return {
        name: 'Yura'
      };
    },
    methods: {}
  }

  export default SimpleHelloWorld;
</script>

<style lang="scss" scoped>

</style>

// AngularStudent/src/app/components/simplehelloworld/simplehelloworld.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-simplehelloworld',
  templateUrl: './simplehelloworld.component.html',
  styleUrls: ['./simplehelloworld.component.scss']
})
export class SimplehelloworldComponent implements OnInit {
  currentDate: string;

  constructor() {
    this.currentDate = new Date().toString();
  }

  ngOnInit(): void {
  }

}

<div>
  <h3>SimpleHelloWorld Component</h3>
  <p>Hello, World!</p>
  <p>{{currentDate}}</p>
</div>
